on: workflow_dispatch

name: Build on Linux
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add PipeWire PPA
        run: "sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream"

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake qt6-base-dev qt6-base-dev-tools qt6-webengine-dev qt6-webengine-dev-tools libqt6webchannel6-dev libx11-dev libpipewire-0.3-dev libxi-dev libwnck-3-dev libappindicator3-dev libpulse-dev"

      - name: Compile
        run: "mkdir build && cd build && cmake .. && cmake --build . --config Release"

      - name: Build debian package
        run: "cd build && make install DESTDIR=../deployment/debian/soundux && cd ../deployment/debian && dpkg-deb --build soundux"

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: Deb package
          path: deployment/debian/soundux.deb
