on: workflow_dispatch

name: Debug on Linux
jobs:
  debug-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake qt6-base-dev qt6-base-dev-tools qt6-webengine-dev libqt6webchannel6-dev libx11-dev libxi-dev libwnck-3-dev libappindicator3-dev libpulse-dev libpipewire-0.3-dev"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        continue-on-error: true
